apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata:
  name: quarkus-greeter-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-repo-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: quarkus-app-deploy-
        labels:
          tekton.dev/pipeline: quarkus-app-deploy
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: quarkus-app-deploy
        params:
          - name: contextDir
            value: greetings-app/java/quarkus-api
          - name: image-name
            value: image-registry.openshift-image-registry.svc:5000/tekton-demo-advanced/quarkus-greet      
          - name: github-repo-url    
            value: $(tt.params.git-repo-url)
          - name: github-repo-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: maven-settings-cm
            configmap:
              name: maven-settings
          - name: shared-pvc
            persistentVolumeClaim:
              claimName: shared-space-pvc
        # Pass the Resources to the Template
        resources:
          - name: appSource
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.git-revision)
                - name: url
                  value: $(tt.params.git-repo-url)