apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata:
  name: quarkus-greeter-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: staging
    - name: git-repo-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: greeter-app-
        labels:
          tekton.dev/pipeline: greeter-app-deploy
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-app-deploy
        params:
          - name: github-repo-url
            value: '$(tt.params.git-repo-url)'
          - name: github-repo-revision
            value: '$(tt.params.git-revision)'
          - name: contextDir
            value: quarkus
        resources:
          - name: appSource
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.git-revision)
                - name: url
                  value: $(tt.params.git-repo-url)
          - name: appImage
            resourceSpec:
              type: image              
              params:
                - name: url
                  # Usng the internal OpenShift Registry
                  value: "image-registry.openshift-image-registry.svc:5000/tekton-demo/quarkus-greet"
