apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app-deploy
spec:
  params:
    - name: contextDir
      description: the context directory from where to build the application
  resources:
    - name: appSource
      type: git
    - name: appImage
      type: image
  tasks:
    # Build the application using the build app task created earlier
    - name: build-java-app
      taskRef:
        name: build-app
      params:
        - name: contextDir
          value: $(params.contextDir)
      resources:
        inputs:
          - name: source
            resource: appSource
        outputs:
          - name: builtImage
            resource: appImage

    # Deploy the application to the kubernets
    - name: deploy-kubernetes-service
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-java-app
      resources:
        inputs:
          - name: source
            resource: appSource
      params:
        - name: ARGS
          value:
            - "apply"
            - "-f"
            - "/workspace/source/k8s/deployment.yaml"
            - "-f"
            - "/workspace/source/k8s/service.yaml"
